language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t davidtie/course-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true davidtie/course-docker-react npm run test
