language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t Tigrin4000/course-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Tigrin4000/course-docker-react npm run test
