language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t davidtie/course-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true davidtie/course-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "course-docker-react"
  env: "Coursedockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-111711926468"
  bucket_path: "course-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
